name: FlameThrower
main: me.petersoj.FlameThrowerPlugin
version: 1.0
description: Adds flame throwing capabilities to Minecraft!
commands:
  flamethrower:
    description: Gives a player a flamethrower with the specified time the fuel tank lasts and amount of refuels (-1 for inifinite)
    usage: /flamethrower <player> <fuel seconds> <amount of refuels>
    permission: flamethrower.give
permissions:
  flamethrower.give:
    default: op