name: FlameThrower
main: me.petersoj.FlameThrowerPlugin
version: 1.0
description: Adds flame throwing capabilities to Minecraft!
commands:
  flamethrower:
    description: Gives a player a flamethrower with specified amount of refuels and if it sets blocks on fire.
    usage: /flamethrower <player> <amount of refuels> <sets blocks on fire>
    permission: flamethrower.give
permissions:
  flamethrower.give:
    default: false